// Mocks generated by Mockito 5.3.0 from annotations
// in ditonton/test/presentation/pages/tv_series_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:ui' as _i14;

import 'package:ditonton/common/state_enum.dart' as _i10;
import 'package:ditonton/domain/entities/episode.dart' as _i12;
import 'package:ditonton/domain/entities/tv.dart' as _i11;
import 'package:ditonton/domain/entities/tv_detail.dart' as _i8;
import 'package:ditonton/domain/usecases/get_episodes.dart' as _i4;
import 'package:ditonton/domain/usecases/get_tv_series_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_tv_series_recommendations.dart'
    as _i3;
import 'package:ditonton/domain/usecases/get_watchlist_tv_series_status.dart'
    as _i5;
import 'package:ditonton/domain/usecases/remove_watchlist_tv_series.dart'
    as _i7;
import 'package:ditonton/domain/usecases/save_watchlist_tv_series.dart' as _i6;
import 'package:ditonton/presentation/provider/tv_series_detail_notifier.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetTvSeriesDetail_0 extends _i1.SmartFake
    implements _i2.GetTvSeriesDetail {
  _FakeGetTvSeriesDetail_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetTvSeriesRecommendations_1 extends _i1.SmartFake
    implements _i3.GetTvSeriesRecommendations {
  _FakeGetTvSeriesRecommendations_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetEpisodes_2 extends _i1.SmartFake implements _i4.GetEpisodes {
  _FakeGetEpisodes_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeGetWatchListTvSeriesStatus_3 extends _i1.SmartFake
    implements _i5.GetWatchListTvSeriesStatus {
  _FakeGetWatchListTvSeriesStatus_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTvSeries_4 extends _i1.SmartFake
    implements _i6.SaveWatchlistTvSeries {
  _FakeSaveWatchlistTvSeries_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistSeries_5 extends _i1.SmartFake
    implements _i7.RemoveWatchlistSeries {
  _FakeRemoveWatchlistSeries_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTvDetail_6 extends _i1.SmartFake implements _i8.TvDetail {
  _FakeTvDetail_6(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [TvSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDetailNotifier extends _i1.Mock
    implements _i9.TvSeriesDetailNotifier {
  MockTvSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvSeriesDetail get getTvSeriesDetail =>
      (super.noSuchMethod(Invocation.getter(#getTvSeriesDetail),
              returnValue: _FakeGetTvSeriesDetail_0(
                  this, Invocation.getter(#getTvSeriesDetail)))
          as _i2.GetTvSeriesDetail);
  @override
  _i3.GetTvSeriesRecommendations get getTvSeriesRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getTvSeriesRecommendations),
              returnValue: _FakeGetTvSeriesRecommendations_1(
                  this, Invocation.getter(#getTvSeriesRecommendations)))
          as _i3.GetTvSeriesRecommendations);
  @override
  _i4.GetEpisodes get getEpisodes =>
      (super.noSuchMethod(Invocation.getter(#getEpisodes),
              returnValue:
                  _FakeGetEpisodes_2(this, Invocation.getter(#getEpisodes)))
          as _i4.GetEpisodes);
  @override
  _i5.GetWatchListTvSeriesStatus get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
              returnValue: _FakeGetWatchListTvSeriesStatus_3(
                  this, Invocation.getter(#getWatchListStatus)))
          as _i5.GetWatchListTvSeriesStatus);
  @override
  _i6.SaveWatchlistTvSeries get saveWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
              returnValue: _FakeSaveWatchlistTvSeries_4(
                  this, Invocation.getter(#saveWatchlist)))
          as _i6.SaveWatchlistTvSeries);
  @override
  _i7.RemoveWatchlistSeries get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
              returnValue: _FakeRemoveWatchlistSeries_5(
                  this, Invocation.getter(#removeWatchlist)))
          as _i7.RemoveWatchlistSeries);
  @override
  _i8.TvDetail get series => (super.noSuchMethod(Invocation.getter(#series),
          returnValue: _FakeTvDetail_6(this, Invocation.getter(#series)))
      as _i8.TvDetail);
  @override
  _i10.RequestState get tvSeriesState =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesState),
          returnValue: _i10.RequestState.Empty) as _i10.RequestState);
  @override
  List<_i11.Tv> get tvSeriesRecommendations =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesRecommendations),
          returnValue: <_i11.Tv>[]) as List<_i11.Tv>);
  @override
  _i10.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i10.RequestState.Empty) as _i10.RequestState);
  @override
  List<_i12.Episode> get episodes =>
      (super.noSuchMethod(Invocation.getter(#episodes),
          returnValue: <_i12.Episode>[]) as List<_i12.Episode>);
  @override
  _i10.RequestState get episodeState =>
      (super.noSuchMethod(Invocation.getter(#episodeState),
          returnValue: _i10.RequestState.Empty) as _i10.RequestState);
  @override
  int get selectedSessionId =>
      (super.noSuchMethod(Invocation.getter(#selectedSessionId), returnValue: 0)
          as int);
  @override
  _i10.RequestState get selectedSeasonIdState =>
      (super.noSuchMethod(Invocation.getter(#selectedSeasonIdState),
          returnValue: _i10.RequestState.Empty) as _i10.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i13.Future<void> fetchTvSeriesDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchTvSeriesDetail, [id]),
              returnValue: _i13.Future<void>.value(),
              returnValueForMissingStub: _i13.Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<void> fetchEpisodesBySessionNumber(
          int? tvId, int? seasonNumber) =>
      (super.noSuchMethod(
              Invocation.method(
                  #fetchEpisodesBySessionNumber, [tvId, seasonNumber]),
              returnValue: _i13.Future<void>.value(),
              returnValueForMissingStub: _i13.Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<void> addWatchlist(_i8.TvDetail? series) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [series]),
              returnValue: _i13.Future<void>.value(),
              returnValueForMissingStub: _i13.Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<void> removeFromWatchlist(_i8.TvDetail? series) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlist, [series]),
              returnValue: _i13.Future<void>.value(),
              returnValueForMissingStub: _i13.Future<void>.value())
          as _i13.Future<void>);
  @override
  _i13.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(Invocation.method(#loadWatchlistStatus, [id]),
              returnValue: _i13.Future<void>.value(),
              returnValueForMissingStub: _i13.Future<void>.value())
          as _i13.Future<void>);
  @override
  void addListener(_i14.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i14.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
